import '../styles/globals.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import { Analytics } from '@vercel/analytics/react';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

const GownBatang = Open_Sans({
  subsets: ['latin'],
  weight: '700',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${GownBatang.className} flex flex-col`}>
        <Header />
        <main className="min-h-screen flex flex-col">
          <div className="grow flex flex-col items-center justify-center">{children}</div>
          <Footer />
        </main>
        <Analytics />
      </body>
    </html>
  );
}
